import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";

const geistOnest = localFont({
  src: "./fonts/Onest/static/Onest-Regular.ttf",
  variable: "--font-onest",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistOnest.variable}`}>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
