import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Header from "../../components/organisms/Header/Header";
import Footer from "../../components/organisms/Footer/Footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const Onest = localFont({
  src: "../fonts/Onest-Regular.woff2",
  variable: "--font-onest",
  weight: "400",
});

const Bitter = localFont({
  src: "../fonts/Bitter-Regular.woff2",
  variable: "--font-bitter",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const messages = await getMessages();

  return (
    <html lang="en">
      <body className={`${Onest.variable} ${Bitter.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <div style={{ display: "flex", flexDirection: "column" }}>
            <Header />
            {children}
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
